import type { Metadata } from 'next'
import { Outfit } from 'next/font/google'
import '../globals.css'
import ProductNavbar from '@/components/Home/Navbar/productNavbar'
import FirstSection from '@/components/Products/FirstSection'
import SecondSection from '@/components/Products/SecondSection'

const outfit = Outfit({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Asana',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={outfit.className}>
        <ProductNavbar />
        <FirstSection />
        <SecondSection />
        {children}
        </body>
    </html>
  )
}
